apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  {{- include "todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: api
  {{- include "todo.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 }}
