apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-web
  labels:
  {{- include "todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.type }}
  selector:
    app: web
  {{- include "todo.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.web.ports | toYaml | nindent 2 }}