apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-mongo
  labels:
    app: mongo
  {{- include "todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.type }}
  selector:
    app: mongo
  {{- include "todo.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mongo.ports | toYaml | nindent 2 }}